-- MySQL Script generated by MySQL Workbench
-- Wed Sep 16 11:06:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`INVENTORY_BIKE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INVENTORY_BIKE` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `STATE_RENT` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BIKE_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BIKE_TYPE` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `PRICE` DOUBLE NULL,
  `TYPE` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BIKE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BIKE` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(500) NULL,
  `IMAGE_URL` VARCHAR(500) NULL,
  `INVENTORY_BIKE_ID` INT(19) NOT NULL,
  `BIKE_TYPE_ID` INT(19) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_BIKE_INVENTORY_BIKE_idx` (`INVENTORY_BIKE_ID` ASC) VISIBLE,
  INDEX `fk_BIKE_BIKE_TYPE1_idx` (`BIKE_TYPE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_BIKE_INVENTORY_BIKE`
    FOREIGN KEY (`INVENTORY_BIKE_ID`)
    REFERENCES `mydb`.`INVENTORY_BIKE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BIKE_BIKE_TYPE1`
    FOREIGN KEY (`BIKE_TYPE_ID`)
    REFERENCES `mydb`.`BIKE_TYPE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `USER_EMAIL` VARCHAR(45) NULL,
  `USER_NAME` VARCHAR(45) NULL,
  `USER_PASSWORD` VARCHAR(45) NULL,
  `USER_RENTSTATUS` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RENT_BIKE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RENT_BIKE` (
  `ID` INT(19) NOT NULL AUTO_INCREMENT,
  `DAILY_DELAY_FEE` DOUBLE NULL,
  `DAYS_CONTRACT` INT(19) NULL,
  `DAYS_REAL` INT(19) NULL,
  `RENT_STATE` VARCHAR(45) NULL,
  `TOTAL_COST` INT(19) NULL,
  `RENT_BIKEcol` VARCHAR(45) NULL,
  `BIKE_ID` INT(19) NOT NULL,
  `USER_ID` INT(19) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_RENT_BIKE_BIKE1_idx` (`BIKE_ID` ASC) VISIBLE,
  INDEX `fk_RENT_BIKE_USER1_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_RENT_BIKE_BIKE1`
    FOREIGN KEY (`BIKE_ID`)
    REFERENCES `mydb`.`BIKE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RENT_BIKE_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `mydb`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER_BIKE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER_BIKE` (
  `USER_ID` INT(19) NOT NULL,
  `BIKE_ID` INT(19) NOT NULL,
  PRIMARY KEY (`USER_ID`, `BIKE_ID`),
  INDEX `fk_USER_has_BIKE_BIKE1_idx` (`BIKE_ID` ASC) VISIBLE,
  INDEX `fk_USER_has_BIKE_USER1_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USER_has_BIKE_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `mydb`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_has_BIKE_BIKE1`
    FOREIGN KEY (`BIKE_ID`)
    REFERENCES `mydb`.`BIKE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
